### PR TITLE
feat: add Option to Control keys

### PR DESCRIPTION
**Pull request by scotch83**
This development adds the option key to the keys to be displayed when only control keys are selected in the preferences

### CODE REVIEW

**Comment by akitchen** [comment]
Thank you for opening a PR, but the option to include the option key in the set of control keys needs to also be a user-facing option for the default visualizer, as option is not a control key, it is a modifier key.

**Comment by akitchen** [comment]
A more ideal solution to this feature request is to have a progression from control keys only, to all modified keys (i.e. shift and option), then all keystrokes. This warrants some thought in the preferences UI as well.

**Comment by scotch83** [comment]
Maybe we can add an option in the preferences or change the label to "only modifier keys"?

**Comment by akitchen** [comment]
I decided to implement this as an option for the default visualizer, it is in the v0.9.17 release

**Comment by scotch83** [comment]
> I decided to implement this as an option for the default visualizer, it is in the v0.9.17 release

Thank you @akitchen  🙏  and sorry for not following up much on this but it's not really a language I am good at hence did not want to waste anyone's time with further non relevant solutions. 

Thank you for implementing this in the new release thou ❤️

**Pull request closed without merging**
