### PR TITLE
Updated Icon for Big Sur

### PR DESCRIPTION
**Pull request by QuintB**
Big Sur released with new app icon guidelines. Rather than lazily paste the current icon onto a white background and calling it a day, I decided to make a new one that kept the spirit of the original.

Here's the PNG in case the .icns isn't viewable on your end. I'm open to feedback about it as well if you want me to tweak something.
KeyCastr

I also made an alternate if this one is nicer
KeyCastrAlt

### CODE REVIEW

**Comment by akitchen** [comment]
Hey @QuintB thanks so much for the PR! The new icon looks really nice, preserving the spirit of the original icon while also modernizing it.

I will merge it locally in order to test but it should preserve your credit for the commit. I'm partial to the first option. Any other thoughts from the community and @keycastr/owners ?

**Comment by elia** [comment]
The first looks great!

**Comment by akitchen** [comment]
I tried it out in a local build and it looks really nice in the app switcher, especially in light mode. In dark mode the tinted shadow is a bit difficult to see.

In order to use this in the next release we would also need a variant without the "shadow", which the app would then display when in inactive mode. This is currently stored in the KeyCastrInactive.icns file.

@QuintB would you be able to produce a similar image for the inactive mode?

**Comment by QuintB** [comment]
Of course, no problem. Do you want me to try to make a dark mode variant too, or rather one that works better in both?

**Comment by QuintB** [comment]
I went ahead and made a few versions, you can see them here.

They're all available in [this zip](https://github.com/keycastr/keycastr/files/6904536/KeyCastr.Icons.zip), I'm not sure if you want me to write the pull again or if I can update it (I'm new here).

Light
Dark

**Comment by akitchen** [comment]
Please go ahead and update the pull request by pushing additional commits, if you could. Thanks!

**Comment by QuintB** [comment]
Okay I think I did it, can you confirm that at least showed up on your end? Thank you :)

**Comment by akitchen** [comment]
Hi @QuintB thank you for pushing some additional changes -- I'll take a closer look next time I have some time to work on KeyCastr. Thanks for your work & patience here!

**Comment by QuintB** [comment]
Of course! Let me know if you need anything else.

**Comment by akitchen** [comment]
Hey @QuintB thanks again. I just tested it out a bit more and these icons look really great. Better late than never!

**Pull request merged**
