### PR TITLE
Add Feature: record recording status after program exited.

### PR DESCRIPTION
**Pull request by spxvszero**
Enhancement refers to this issue.
#256

### CODE REVIEW

**Comment by akitchen** [comment]
Hey @spxvszero thank you for opening a pull request to address this issue. I'm thinking a bit more about this possible feature while working on a next version and will get to this soon. 

Given the confusion some people run into when KeyCastr lacks permissions on their machine, I'm worried that this feature could potentially make things more complicated/confusing. That said, thank you for taking the time to implement this and open a PR 👍

**Comment by spxvszero** [comment]
I see, looking forward to your new version.

**Comment by akitchen** [comment]
I didn't necessarily mean to close this, although I can see how my reply was a bit ambiguous.

In order to support this I think the app needs to better differentiate between missing permissions vs. the user having turned off event broadcasting. This is not something I've been able to put much thought into yet however, as what time I have for KeyCastr is focused on improving the mouse event visualization features.

**Comment by akitchen** [comment]
Continuing to think about better ways of handling and displaying permission errors, but for now I'm going to close this. Thanks again for opening a PR.

**Pull request closed without merging**
