### PR TITLE
Fixes uppercase string display issues for non-qwerty layouts

### PR DESCRIPTION
**Pull request by akitchen**
Also includes some Xcode internal housekeeping

### CODE REVIEW

**Comment by akitchen** [comment]
This fixes #76

**Comment by akitchen** [comment]
I'm going to merge this and make a release for easier testing by others.

**Comment by qguv** [comment]
Current homebrew version (0.9.3) still has this problem. Would it be possible to push this commit out with a 0.9.4 version to Homebrew?

**Comment by akitchen** [comment]
This is awaiting merge now - https://github.com/caskroom/homebrew-cask/pull/36077

**Pull request merged**
