### PR TITLE
Redesigned icon and added 2x version for Retina.

### PR DESCRIPTION
**Pull request by darenju**
I started using KeyCastr on my MacBook Pro Retina and it works well.
However, the icon in the menu bar is not Retina-ready, so it looks sort of ugly in there.

That's why I opened up Sketch and re-designed the icon to look the same and export it at both 1x and 2x resolution.

### CODE REVIEW

**Comment by akitchen** [comment]
Very cool. Thank you!

**Comment by darenju** [comment]
You're welcome. I tried to make the same icon as before, so old users wouldn't see a difference.

However I have no idea how Xcode handles this, so I let you do this job.

**Comment by akitchen** [comment]
No problem.  The code on master now has the @2x icons added to the app.  Thanks again.

**Comment by darenju** [comment]
Awesome. When will it come in an update?

**Comment by lqez** [comment]
Nice work!

**Pull request merged**
